# ============================================
# Apache Spark - Configuração Padrão
# ============================================

# Endereço do Master
spark.master                        spark://spark-master:7077

# Event Log (histórico de jobs)
spark.eventLog.enabled              true
spark.eventLog.dir                  /tmp/spark-events
spark.history.fs.logDirectory       /tmp/spark-events

# Reverse Proxy (permite navegar nas UIs dos Workers via Master UI)
spark.ui.reverseProxy               true
